const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || "https://whatsapp.com/channel/0029VaeKIQODuMRWLSIIbf2R"                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";

global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029VaeKIQODuMRWLSIIbf2R";




global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "9203289479116";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "true"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "true"
global.readmessage = process.env.READ_MESSAGE || "true"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "true"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923289479116";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_18_18_07_03_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjI0LFxuICAgICAgICAxNjcsXG4gICAgICAgIDMwLFxuICAgICAgICA2NixcbiAgICAgICAgMTI2LFxuICAgICAgICAyMDYsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMTI0LFxuICAgICAgICAxMCxcbiAgICAgICAgNjAsXG4gICAgICAgIDYzLFxuICAgICAgICAyMzYsXG4gICAgICAgIDY4LFxuICAgICAgICAyNDYsXG4gICAgICAgIDE2MixcbiAgICAgICAgMTEzLFxuICAgICAgICAyMjUsXG4gICAgICAgIDExMixcbiAgICAgICAgMzAsXG4gICAgICAgIDg1LFxuICAgICAgICA2MyxcbiAgICAgICAgNTUsXG4gICAgICAgIDM0LFxuICAgICAgICAzMyxcbiAgICAgICAgMTIyLFxuICAgICAgICA3NixcbiAgICAgICAgMjIxLFxuICAgICAgICAyMDEsXG4gICAgICAgIDU2LFxuICAgICAgICA4NCxcbiAgICAgICAgODYsXG4gICAgICAgIDExOFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNTQsXG4gICAgICAgIDQsXG4gICAgICAgIDU2LFxuICAgICAgICAxNzcsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMTI2LFxuICAgICAgICA4OSxcbiAgICAgICAgMTUzLFxuICAgICAgICAyMixcbiAgICAgICAgMTkwLFxuICAgICAgICAxMjgsXG4gICAgICAgIDExMSxcbiAgICAgICAgOTAsXG4gICAgICAgIDEzNixcbiAgICAgICAgMjQxLFxuICAgICAgICAxNjYsXG4gICAgICAgIDY5LFxuICAgICAgICAxMjksXG4gICAgICAgIDIxOSxcbiAgICAgICAgNyxcbiAgICAgICAgMTczLFxuICAgICAgICAzNCxcbiAgICAgICAgNDUsXG4gICAgICAgIDE4NyxcbiAgICAgICAgMjUzLFxuICAgICAgICAxMjEsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMjcsXG4gICAgICAgIDExOSxcbiAgICAgICAgMzEsXG4gICAgICAgIDc0LFxuICAgICAgICAxMjZcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTA3LFxuICAgICAgICA5NixcbiAgICAgICAgMzMsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMjE1LFxuICAgICAgICA5NCxcbiAgICAgICAgMTAyLFxuICAgICAgICA5MCxcbiAgICAgICAgMTAzLFxuICAgICAgICAyNTEsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMTA5LFxuICAgICAgICAxNjUsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMTA4LFxuICAgICAgICAzNyxcbiAgICAgICAgMTY2LFxuICAgICAgICAxNzksXG4gICAgICAgIDE4LFxuICAgICAgICAxODQsXG4gICAgICAgIDE0NixcbiAgICAgICAgMjM4LFxuICAgICAgICAxNTksXG4gICAgICAgIDIzLFxuICAgICAgICAxMjksXG4gICAgICAgIDI2LFxuICAgICAgICAyMzcsXG4gICAgICAgIDE4NCxcbiAgICAgICAgOTEsXG4gICAgICAgIDksXG4gICAgICAgIDc1XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIzMSxcbiAgICAgICAgMzQsXG4gICAgICAgIDIzNixcbiAgICAgICAgODcsXG4gICAgICAgIDEwNixcbiAgICAgICAgNixcbiAgICAgICAgOTIsXG4gICAgICAgIDgzLFxuICAgICAgICAyMzAsXG4gICAgICAgIDI1MixcbiAgICAgICAgMTMyLFxuICAgICAgICAyMyxcbiAgICAgICAgMTYsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMTg2LFxuICAgICAgICAzMCxcbiAgICAgICAgMTYzLFxuICAgICAgICA3MixcbiAgICAgICAgMTM1LFxuICAgICAgICAxMzgsXG4gICAgICAgIDQ5LFxuICAgICAgICA5MSxcbiAgICAgICAgMTQ3LFxuICAgICAgICA1NixcbiAgICAgICAgMTg4LFxuICAgICAgICAyNTEsXG4gICAgICAgIDgwLFxuICAgICAgICAxNDcsXG4gICAgICAgIDEwOCxcbiAgICAgICAgMTk0LFxuICAgICAgICAxODgsXG4gICAgICAgIDU2XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA5NixcbiAgICAgICAgMTQ1LFxuICAgICAgICAwLFxuICAgICAgICA2NCxcbiAgICAgICAgNzMsXG4gICAgICAgIDE1NixcbiAgICAgICAgMTQ5LFxuICAgICAgICAyMDMsXG4gICAgICAgIDE2NCxcbiAgICAgICAgMTUsXG4gICAgICAgIDI3LFxuICAgICAgICAxMDYsXG4gICAgICAgIDgxLFxuICAgICAgICAyMjgsXG4gICAgICAgIDM4LFxuICAgICAgICAxODMsXG4gICAgICAgIDI1LFxuICAgICAgICAxNzIsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMTc0LFxuICAgICAgICAyMzgsXG4gICAgICAgIDEwMCxcbiAgICAgICAgOTIsXG4gICAgICAgIDQzLFxuICAgICAgICA5NCxcbiAgICAgICAgOTAsXG4gICAgICAgIDc2LFxuICAgICAgICAyNTUsXG4gICAgICAgIDE0MixcbiAgICAgICAgMTY1LFxuICAgICAgICAxMjYsXG4gICAgICAgIDc5XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDI0OCxcbiAgICAgICAgMTcxLFxuICAgICAgICAxOCxcbiAgICAgICAgMzEsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMjEwLFxuICAgICAgICAxNzIsXG4gICAgICAgIDczLFxuICAgICAgICAxMjIsXG4gICAgICAgIDEwMCxcbiAgICAgICAgNDAsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMTQwLFxuICAgICAgICAxNTAsXG4gICAgICAgIDY1LFxuICAgICAgICAyNTEsXG4gICAgICAgIDg0LFxuICAgICAgICAxMzUsXG4gICAgICAgIDE3NCxcbiAgICAgICAgNjgsXG4gICAgICAgIDY4LFxuICAgICAgICA1OCxcbiAgICAgICAgMjE1LFxuICAgICAgICAyMTUsXG4gICAgICAgIDEyNCxcbiAgICAgICAgNzMsXG4gICAgICAgIDIzNyxcbiAgICAgICAgMTM0LFxuICAgICAgICAxMTksXG4gICAgICAgIDIzOCxcbiAgICAgICAgMjEzLFxuICAgICAgICAxMFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAyMzIsXG4gICAgICAgICAgMTAsXG4gICAgICAgICAgNDMsXG4gICAgICAgICAgMTc4LFxuICAgICAgICAgIDE1OSxcbiAgICAgICAgICAxMjIsXG4gICAgICAgICAgODUsXG4gICAgICAgICAgMTg4LFxuICAgICAgICAgIDMyLFxuICAgICAgICAgIDUwLFxuICAgICAgICAgIDE3NCxcbiAgICAgICAgICA2MCxcbiAgICAgICAgICAxMjIsXG4gICAgICAgICAgNzMsXG4gICAgICAgICAgMTQ2LFxuICAgICAgICAgIDIxNyxcbiAgICAgICAgICA2NyxcbiAgICAgICAgICAxNjMsXG4gICAgICAgICAgMjEzLFxuICAgICAgICAgIDE0MCxcbiAgICAgICAgICAyMTUsXG4gICAgICAgICAgMjEwLFxuICAgICAgICAgIDI1MCxcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgMTE4LFxuICAgICAgICAgIDE0NSxcbiAgICAgICAgICAxMjYsXG4gICAgICAgICAgMjUyLFxuICAgICAgICAgIDk4LFxuICAgICAgICAgIDIxLFxuICAgICAgICAgIDY0LFxuICAgICAgICAgIDExOFxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAyMzksXG4gICAgICAgICAgNTQsXG4gICAgICAgICAgMjM5LFxuICAgICAgICAgIDEzNyxcbiAgICAgICAgICAyMDgsXG4gICAgICAgICAgNzEsXG4gICAgICAgICAgMTIsXG4gICAgICAgICAgMjExLFxuICAgICAgICAgIDEyOSxcbiAgICAgICAgICAxOTMsXG4gICAgICAgICAgMjI5LFxuICAgICAgICAgIDI0MyxcbiAgICAgICAgICAyNTQsXG4gICAgICAgICAgMjMwLFxuICAgICAgICAgIDI0NyxcbiAgICAgICAgICAxMjUsXG4gICAgICAgICAgMTk3LFxuICAgICAgICAgIDEzNCxcbiAgICAgICAgICAxMzIsXG4gICAgICAgICAgMTgyLFxuICAgICAgICAgIDUsXG4gICAgICAgICAgMTIzLFxuICAgICAgICAgIDIxMixcbiAgICAgICAgICAyMDcsXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgOTEsXG4gICAgICAgICAgMTM4LFxuICAgICAgICAgIDE0MixcbiAgICAgICAgICAxOTYsXG4gICAgICAgICAgMjQsXG4gICAgICAgICAgMTQ0LFxuICAgICAgICAgIDE2XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNjEsXG4gICAgICAgIDExNCxcbiAgICAgICAgNDEsXG4gICAgICAgIDYxLFxuICAgICAgICAzNyxcbiAgICAgICAgMjAsXG4gICAgICAgIDI0NixcbiAgICAgICAgMjMzLFxuICAgICAgICAwLFxuICAgICAgICAxNDgsXG4gICAgICAgIDI1MCxcbiAgICAgICAgNjYsXG4gICAgICAgIDExMCxcbiAgICAgICAgMjI0LFxuICAgICAgICAxOTgsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMjMyLFxuICAgICAgICAxNDIsXG4gICAgICAgIDE1LFxuICAgICAgICAxOCxcbiAgICAgICAgODksXG4gICAgICAgIDY2LFxuICAgICAgICA0MixcbiAgICAgICAgMjAyLFxuICAgICAgICA4LFxuICAgICAgICAxNTgsXG4gICAgICAgIDI0OSxcbiAgICAgICAgMTc3LFxuICAgICAgICAzNCxcbiAgICAgICAgMjQzLFxuICAgICAgICAxMDksXG4gICAgICAgIDE1OCxcbiAgICAgICAgMTg5LFxuICAgICAgICAxMDcsXG4gICAgICAgIDI2LFxuICAgICAgICAxMzcsXG4gICAgICAgIDUyLFxuICAgICAgICAyMzUsXG4gICAgICAgIDIzOSxcbiAgICAgICAgMTE2LFxuICAgICAgICAyMzMsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMTcsXG4gICAgICAgIDE3MSxcbiAgICAgICAgNDcsXG4gICAgICAgIDExNixcbiAgICAgICAgMjE4LFxuICAgICAgICAxMzksXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTgzLFxuICAgICAgICA1LFxuICAgICAgICAyMjgsXG4gICAgICAgIDUyLFxuICAgICAgICAxNjQsXG4gICAgICAgIDI0OCxcbiAgICAgICAgODIsXG4gICAgICAgIDEwMixcbiAgICAgICAgOTQsXG4gICAgICAgIDE1MixcbiAgICAgICAgMTUzLFxuICAgICAgICA3NixcbiAgICAgICAgMTA5LFxuICAgICAgICA0NCxcbiAgICAgICAgMTM2XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAzOSxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJoQm1HRDczWU8rdWpWS2ZIOW9KamY5UmVDemhzNXdWODkxbjd0T3U1T2xnPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjkyMzI4OTQ3OTExNkBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiQzY4MEREODJDNzAxMkRDODcwNTM5QzFCODcyRTVFRjFcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzIwMDMwNzA5XG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTIzMjg5NDc5MTE2QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI2NDA0REJFNEYzMEM0MDdDMTM4OEM2MDc0Mzc1MDVGRlwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjAwMzA3MTBcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5MjMyODk0NzkxMTZAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjU3REVDNzNCNDUzNkM2OTg5RTRBMzg4Qzg5NjY3OTM5XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyMDAzMDcxMlxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjkyMzI4OTQ3OTExNkBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiMzc3NjFCQTcyQTE4MzI2REYwOUU5M0YwMTJGODE2QTlcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzIwMDMwNzEzXG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMSxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcIlpRVmx4VF9OU3FTdTZUSU9WbXB5b2dcIixcbiAgXCJwaG9uZUlkXCI6IFwiNTFiYWIzYmItMjJkNy00OTZkLWFkODgtZTk5YjM4NGJlOGJjXCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDcwLFxuICAgICAgMTQyLFxuICAgICAgMzUsXG4gICAgICA1MCxcbiAgICAgIDE4MSxcbiAgICAgIDcsXG4gICAgICA0MixcbiAgICAgIDM3LFxuICAgICAgMjE0LFxuICAgICAgMTkwLFxuICAgICAgMTMsXG4gICAgICAzLFxuICAgICAgMTExLFxuICAgICAgMjE1LFxuICAgICAgNjYsXG4gICAgICAxNjQsXG4gICAgICAxNDcsXG4gICAgICAyMzYsXG4gICAgICA0MyxcbiAgICAgIDBcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMjcsXG4gICAgICA5OSxcbiAgICAgIDE2NixcbiAgICAgIDI1MCxcbiAgICAgIDEwLFxuICAgICAgODUsXG4gICAgICA3OSxcbiAgICAgIDUwLFxuICAgICAgMTAxLFxuICAgICAgMTQ1LFxuICAgICAgMTI5LFxuICAgICAgMjEyLFxuICAgICAgMjI3LFxuICAgICAgMTI3LFxuICAgICAgMjYsXG4gICAgICAyMzgsXG4gICAgICAyMzQsXG4gICAgICAyMTgsXG4gICAgICAxMzYsXG4gICAgICAxOTJcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiVkZQS00xTkNcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjkyMzI4OTQ3OTExNjoyQHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJuYW1lXCI6IFwiT2xtYXggQ2FycnlcIixcbiAgICBcImxpZFwiOiBcIjE2MjYwNzk5ODc0Njg1NToyQGxpZFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ1A2THM3QUZFUENybHJRR0dBRWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiOGlxNFY1cUJVcHBOZUhuRGxoZnVvNFlXWk12bkw1T1oweUJaSTdNVG4wRT1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJoQTZKTUZoSGxweGRoWDduM0kzK1Jqa3dYQWkyWmVvVXlrSDRMT20xdHp2MFZwdEVSbWgyc2MwdWxLUjhJZGZBdHQ2RXVIcmlBRHJjMFFyS01QaTdCZz09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJ3NTNadTdyckpJNWdqY05OQTBDMllMWWtkeWhGcVZjWVlRQnM4d0VFNGVxcnJPTndwVzZDOEE5S01ndEV5UUs0Nm03cHV0Qk10Sm5HUXQ3VjhEcDJpQT09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCI5MjMyODk0NzkxMTY6MkBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDI0MixcbiAgICAgICAgICA0MixcbiAgICAgICAgICAxODQsXG4gICAgICAgICAgODcsXG4gICAgICAgICAgMTU0LFxuICAgICAgICAgIDEyOSxcbiAgICAgICAgICA4MixcbiAgICAgICAgICAxNTQsXG4gICAgICAgICAgNzcsXG4gICAgICAgICAgMTIwLFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICAxOTUsXG4gICAgICAgICAgMTUwLFxuICAgICAgICAgIDIzLFxuICAgICAgICAgIDIzOCxcbiAgICAgICAgICAxNjMsXG4gICAgICAgICAgMTM0LFxuICAgICAgICAgIDIyLFxuICAgICAgICAgIDEwMCxcbiAgICAgICAgICAyMDMsXG4gICAgICAgICAgMjMxLFxuICAgICAgICAgIDQ3LFxuICAgICAgICAgIDE0NyxcbiAgICAgICAgICAxNTMsXG4gICAgICAgICAgMjExLFxuICAgICAgICAgIDMyLFxuICAgICAgICAgIDg5LFxuICAgICAgICAgIDM1LFxuICAgICAgICAgIDE3OSxcbiAgICAgICAgICAxOSxcbiAgICAgICAgICAxNTksXG4gICAgICAgICAgNjVcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcInNtYmFcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcyMDAzMDcwOCxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQUZvRFwiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBRm9ELmpzb24iOiAie1wia2V5RGF0YVwiOlwiWkhlQkJaaWlZbUlMam9tR0FsQ0pPV2lvVHlPcWVxbTNqM04wMXBHVGNOUT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxNDQzNjc3Njk0LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MjAwMzA3MTA1NjBcIn0iCn0="  // PUT your SESSION_ID 


module.exports = {

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.8",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "Sheikh",
  ownername:process.env.OWNER_NAME|| "MUQSIT",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "public",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
